#!/bin/bash

repo="sparebank1utvikling/app-configrepo-sb1u"

if ! command -v gh 2>&1 >/dev/null
then
    echo "GitHub cli 'gh' could not be found"
    exit 1
fi

(cd $DEVENV_DIR/src && pipenv run python3 prod.py)